server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://ev2b833.edc.tpp.tsysecom.com:3100/loki/api/v1/push


scrape_configs:
- job_name: journal
  journal:
    labels:
      job: systemd-journal
    path: /var/log/journal
  relabel_configs:
  - source_labels:
    - __journal__systemd_unit
    target_label: system_unit
  - source_labels:
    - __journal_priority
    target_label: system_priority
  - source_labels:
    - __journal__hostname
    target_label: system_hostname
  - source_labels:
    - __journal__transport
    target_label: system_transport
  - action: drop
    regex: .+
    source_labels:
    - __journal__audit_id
  - source_labels: ['__journal_container_name']
    regex: ^([^_]+)_([^\._]+)(\.([^_]+))?_([^_]+)_([^_]+)_[^_]+_[^_]+$
    target_label: 'namespace'
    replacement: '${6}'

  - source_labels: ['__journal_container_name']
    regex: ^([^_]+)_([^\._]+)(\.([^_]+))?_([^_]+)_([^_]+)_[^_]+_[^_]+$
    target_label: 'instance'
    replacement: '${5}'

  - source_labels: ['__journal_container_name']
    regex: ^([^_]+)_([^\._]+)(\.([^_]+))?_([^_]+)_([^_]+)_[^_]+_[^_]+$
    target_label: 'container_name'
    replacement: '${2}'


