apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"promtail","namespace":"loki"}}
  creationTimestamp: "2021-03-12T11:53:57Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:secrets:
        .: {}
        k:{"name":"promtail-token-pj92n"}:
          .: {}
          f:name: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-03-12T11:53:57Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-03-12T11:53:57Z"
  name: promtail
  namespace: loki
  resourceVersion: "4866474"
  selfLink: /api/v1/namespaces/loki/serviceaccounts/promtail
  uid: d7904ac6-bbf3-4098-921f-d242f0aa85d9
secrets:
- name: promtail-token-pj92n
