apiVersion: v1
kind: Service
metadata:
  name: memcached
  namespace: loki
  
spec:
  clusterIP: None
  ports:
  - name: memcached-client
    port: 11211
    protocol: TCP
    targetPort: 11211
  - name: exporter-http-metrics
    port: 9150
    protocol: TCP
    targetPort: 9150
  selector:
    name: memcached
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
