apiVersion: v1
kind: Service
metadata:
  name: ingester
  namespace: loki
  
spec:
  ports:
  - name: ingester-http-metrics
    port: 3100
    protocol: TCP
    targetPort: 3100
  - name: ingester-grpc
    port: 9095
    protocol: TCP
    targetPort: 9095
  selector:
    name: ingester
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
