apiVersion: v1
kind: Service
metadata:
  name: querier
  namespace: loki
  
spec:
 
  ports:
  - name: querier-http-metrics
    port: 3100
    protocol: TCP
    targetPort: 3100
  - name: querier-grpc
    port: 9095
    protocol: TCP
    targetPort: 9095
  selector:
    name: querier
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
