apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"name":"memcached"},"name":"memcached","namespace":"loki"},"spec":{"clusterIP":"None","ports":[{"name":"memcached-client","port":11211,"targetPort":11211},{"name":"exporter-http-metrics","port":9150,"targetPort":9150}],"selector":{"name":"memcached"}}}
  creationTimestamp: "2021-03-12T11:54:08Z"
  labels:
    name: memcached
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:name: {}
      f:spec:
        f:clusterIP: {}
        f:ports:
          .: {}
          k:{"port":9150,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
          k:{"port":11211,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:name: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-03-12T11:54:08Z"
  name: memcached
  namespace: loki
  resourceVersion: "4866568"
  selfLink: /api/v1/namespaces/loki/services/memcached
  uid: c2d03f90-b55c-4b25-87e6-ed30768feaf7
spec:
  clusterIP: None
  ports:
  - name: memcached-client
    port: 11211
    protocol: TCP
    targetPort: 11211
  - name: exporter-http-metrics
    port: 9150
    protocol: TCP
    targetPort: 9150
  selector:
    name: memcached
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
