apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: loki
  
spec:
  ports:
  - name: consul-server
    port: 8300
    protocol: TCP
    targetPort: 8300
  - name: consul-serf
    port: 8301
    protocol: TCP
    targetPort: 8301
  - name: consul-client
    port: 8400
    protocol: TCP
    targetPort: 8400
  - name: consul-api
    port: 8500
    protocol: TCP
    targetPort: 8500
  - name: statsd-exporter-http-metrics
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: consul-exporter-http-metrics
    port: 9107
    protocol: TCP
    targetPort: 9107
  selector:
    name: consul
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
