apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"name":"ingester"},"name":"ingester","namespace":"loki"},"spec":{"ports":[{"name":"ingester-http-metrics","port":3100,"targetPort":3100},{"name":"ingester-grpc","port":9095,"targetPort":9095}],"selector":{"name":"ingester"}}}
  creationTimestamp: "2021-03-12T11:54:08Z"
  labels:
    name: ingester
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:name: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":3100,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
          k:{"port":9095,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:name: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-03-12T11:54:08Z"
  name: ingester
  namespace: loki
  resourceVersion: "4866564"
  selfLink: /api/v1/namespaces/loki/services/ingester
  uid: 2f95120c-fa96-4816-af09-a2b42e168c57
spec:
  clusterIP: 10.104.0.57
  ports:
  - name: ingester-http-metrics
    port: 3100
    protocol: TCP
    targetPort: 3100
  - name: ingester-grpc
    port: 9095
    protocol: TCP
    targetPort: 9095
  selector:
    name: ingester
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
