apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: loki
  
spec:
  ports:
  - name: nginx-http
    port: 80
    protocol: TCP
    targetPort: 80
    #nodePort: 32091
  selector:
    name: gateway
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
