apiVersion: v1
kind: Service
metadata:
  name: table-manager
  namespace: loki
  
spec:
  
  ports:
  - name: table-manager-http-metrics
    port: 3100
    protocol: TCP
    targetPort: 3100
  - name: table-manager-grpc
    port: 9095
    protocol: TCP
    targetPort: 9095
  selector:
    name: table-manager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
