apiVersion: v1
kind: Service
metadata:
  name: query-frontend
  namespace: loki
  
spec:
  clusterIP: None
  ports:
  - name: query-frontend-http-metrics
    port: 3100
    protocol: TCP
    targetPort: 3100
  - name: query-frontend-grpc
    port: 9095
    protocol: TCP
    targetPort: 9095
  publishNotReadyAddresses: true
  selector:
    name: query-frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
