apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"name":"memcached-frontend"},"name":"memcached-frontend","namespace":"loki"},"spec":{"clusterIP":"None","ports":[{"name":"memcached-client","port":11211,"targetPort":11211},{"name":"exporter-http-metrics","port":9150,"targetPort":9150}],"selector":{"name":"memcached-frontend"}}}
  creationTimestamp: "2021-03-12T11:54:09Z"
  labels:
    name: memcached-frontend
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:name: {}
      f:spec:
        f:clusterIP: {}
        f:ports:
          .: {}
          k:{"port":9150,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
          k:{"port":11211,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:name: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-03-12T11:54:09Z"
  name: memcached-frontend
  namespace: loki
  resourceVersion: "4866577"
  selfLink: /api/v1/namespaces/loki/services/memcached-frontend
  uid: 9507e90b-6abf-4cc0-a493-2cd851128cd0
spec:
  clusterIP: None
  ports:
  - name: memcached-client
    port: 11211
    protocol: TCP
    targetPort: 11211
  - name: exporter-http-metrics
    port: 9150
    protocol: TCP
    targetPort: 9150
  selector:
    name: memcached-frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
