apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"name":"query-frontend"},"name":"query-frontend","namespace":"loki"},"spec":{"clusterIP":"None","ports":[{"name":"query-frontend-http-metrics","port":3100,"targetPort":3100},{"name":"query-frontend-grpc","port":9095,"targetPort":9095}],"publishNotReadyAddresses":true,"selector":{"name":"query-frontend"}}}
  creationTimestamp: "2021-03-12T11:54:11Z"
  labels:
    name: query-frontend
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:name: {}
      f:spec:
        f:clusterIP: {}
        f:ports:
          .: {}
          k:{"port":3100,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
          k:{"port":9095,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:publishNotReadyAddresses: {}
        f:selector:
          .: {}
          f:name: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-03-12T11:54:11Z"
  name: query-frontend
  namespace: loki
  resourceVersion: "4866614"
  selfLink: /api/v1/namespaces/loki/services/query-frontend
  uid: 2b4bfe9f-8c53-4b9c-93d9-202c94c852b8
spec:
  clusterIP: None
  ports:
  - name: query-frontend-http-metrics
    port: 3100
    protocol: TCP
    targetPort: 3100
  - name: query-frontend-grpc
    port: 9095
    protocol: TCP
    targetPort: 9095
  publishNotReadyAddresses: true
  selector:
    name: query-frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
