apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"name":"consul-sidekick","namespace":"loki"},"rules":[{"apiGroups":["","extensions","apps"],"resources":["pods","replicasets"],"verbs":["get","list","watch"]}]}
  creationTimestamp: "2021-03-12T11:54:03Z"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:rules: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-03-12T11:54:03Z"
  name: consul-sidekick
  namespace: loki
  resourceVersion: "4866515"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/loki/roles/consul-sidekick
  uid: bccad131-31e0-487f-a4e2-4eaf50a82069
rules:
- apiGroups:
  - ""
  - extensions
  - apps
  resources:
  - pods
  - replicasets
  verbs:
  - get
  - list
  - watch
