apiVersion: v1
data:
  config.yaml: |
    chunk_store_config:
        chunk_cache_config:
            memcached:
                batch_size: 100
                parallelism: 100
            memcached_client:
                consistent_hash: true
                host: memcached.loki.svc.cluster.local
                service: memcached-client
        max_look_back_period: 0
        write_dedupe_cache_config:
            memcached:
                batch_size: 100
                parallelism: 100
            memcached_client:
                consistent_hash: true
                host: memcached-index-writes.loki.svc.cluster.local
                service: memcached-client
    distributor:
        ring:
            kvstore:
                consul:
                    consistent_reads: false
                    host: consul.loki.svc.cluster.local:8500
                    http_client_timeout: 20s
                    watch_burst_size: 1
                    watch_rate_limit: 1
                store: consul
    frontend:
        compress_responses: true
        log_queries_longer_than: 5s
        max_outstanding_per_tenant: 256
    frontend_worker:
        frontend_address: query-frontend.loki.svc.cluster.local:9095
        grpc_client_config:
            max_send_msg_size: 1.048576e+08
        parallelism: 2
    ingester:
        chunk_block_size: 262144
        chunk_idle_period: 15m
        lifecycler:
            heartbeat_period: 5s
            interface_names:
              - eth0
            join_after: 30s
            num_tokens: 512
            ring:
                heartbeat_timeout: 1m
                kvstore:
                    consul:
                        consistent_reads: true
                        host: consul.loki.svc.cluster.local:8500
                        http_client_timeout: 20s
                    store: consul
                replication_factor: 3
        max_transfer_retries: 60
    ingester_client:
        grpc_client_config:
            max_recv_msg_size: 6.7108864e+07
        remote_timeout: 1s
    limits_config:
        enforce_metric_name: false
        ingestion_burst_size_mb: 20
        ingestion_rate_mb: 10
        ingestion_rate_strategy: global
        max_cache_freshness_per_query: 10m
        max_global_streams_per_user: 10000
        max_query_length: 12000h
        max_query_parallelism: 16
        max_streams_per_user: 0
        reject_old_samples: true
        reject_old_samples_max_age: 168h
    querier:
        query_ingesters_within: 2h
    query_range:
        align_queries_with_step: true
        cache_results: true
        max_retries: 5
        results_cache:
            cache:
                memcached_client:
                    consistent_hash: true
                    host: memcached-frontend.loki.svc.cluster.local
                    max_idle_conns: 16
                    service: memcached-client
                    timeout: 500ms
                    update_interval: 1m
        split_queries_by_interval: 30m
    ruler: {}
    schema_config:
        configs:
          - from: "2020-10-24"
            index:
                period: 24h
                prefix: loki_index_
            object_store: aws
            schema: v11
            store: aws
    server:
        graceful_shutdown_timeout: 5s
        grpc_server_max_concurrent_streams: 1000
        grpc_server_max_recv_msg_size: 1.048576e+08
        grpc_server_max_send_msg_size: 1.048576e+08
        http_listen_port: 3100
        http_server_idle_timeout: 120s
        http_server_write_timeout: 1m
    storage_config:
        aws:
            dynamodb:
                dynamodb_url: dynamodb://us-east-1
            s3: s3://s3://us-east-1/sre-logging-devsyntheticdigitalinnov-us-east-1-tsys
            s3forcepathstyle: false
        index_queries_cache_config:
            memcached:
                batch_size: 100
                parallelism: 100
            memcached_client:
                consistent_hash: true
                host: memcached-index-queries.loki.svc.cluster.local
                service: memcached-client
    table_manager:
        creation_grace_period: 3h
        poll_interval: 10m
        retention_deletes_enabled: false
        retention_period: 0
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yaml":"chunk_store_config:\n    chunk_cache_config:\n        memcached:\n            batch_size: 100\n            parallelism: 100\n        memcached_client:\n            consistent_hash: true\n            host: memcached.loki.svc.cluster.local\n            service: memcached-client\n    max_look_back_period: 0\n    write_dedupe_cache_config:\n        memcached:\n            batch_size: 100\n            parallelism: 100\n        memcached_client:\n            consistent_hash: true\n            host: memcached-index-writes.loki.svc.cluster.local\n            service: memcached-client\ndistributor:\n    ring:\n        kvstore:\n            consul:\n                consistent_reads: false\n                host: consul.loki.svc.cluster.local:8500\n                http_client_timeout: 20s\n                watch_burst_size: 1\n                watch_rate_limit: 1\n            store: consul\nfrontend:\n    compress_responses: true\n    log_queries_longer_than: 5s\n    max_outstanding_per_tenant: 256\nfrontend_worker:\n    frontend_address: query-frontend.loki.svc.cluster.local:9095\n    grpc_client_config:\n        max_send_msg_size: 1.048576e+08\n    parallelism: 2\ningester:\n    chunk_block_size: 262144\n    chunk_idle_period: 15m\n    lifecycler:\n        heartbeat_period: 5s\n        interface_names:\n          - eth0\n        join_after: 30s\n        num_tokens: 512\n        ring:\n            heartbeat_timeout: 1m\n            kvstore:\n                consul:\n                    consistent_reads: true\n                    host: consul.loki.svc.cluster.local:8500\n                    http_client_timeout: 20s\n                store: consul\n            replication_factor: 3\n    max_transfer_retries: 60\ningester_client:\n    grpc_client_config:\n        max_recv_msg_size: 6.7108864e+07\n    remote_timeout: 1s\nlimits_config:\n    enforce_metric_name: false\n    ingestion_burst_size_mb: 20\n    ingestion_rate_mb: 10\n    ingestion_rate_strategy: global\n    max_cache_freshness_per_query: 10m\n    max_global_streams_per_user: 10000\n    max_query_length: 12000h\n    max_query_parallelism: 16\n    max_streams_per_user: 0\n    reject_old_samples: true\n    reject_old_samples_max_age: 168h\nquerier:\n    query_ingesters_within: 2h\nquery_range:\n    align_queries_with_step: true\n    cache_results: true\n    max_retries: 5\n    results_cache:\n        cache:\n            memcached_client:\n                consistent_hash: true\n                host: memcached-frontend.loki.svc.cluster.local\n                max_idle_conns: 16\n                service: memcached-client\n                timeout: 500ms\n                update_interval: 1m\n    split_queries_by_interval: 30m\nruler: {}\nschema_config:\n    configs:\n      - from: \"2020-10-24\"\n        index:\n            period: 24h\n            prefix: loki_index_\n        object_store: aws\n        schema: v11\n        store: aws\nserver:\n    graceful_shutdown_timeout: 5s\n    grpc_server_max_concurrent_streams: 1000\n    grpc_server_max_recv_msg_size: 1.048576e+08\n    grpc_server_max_send_msg_size: 1.048576e+08\n    http_listen_port: 3100\n    http_server_idle_timeout: 120s\n    http_server_write_timeout: 1m\nstorage_config:\n    aws:\n        dynamodb:\n            dynamodb_url: dynamodb://us-east-1\n        s3: s3://s3://us-east-1/sre-logging-devsyntheticdigitalinnov-us-east-1-tsys\n        s3forcepathstyle: false\n    index_queries_cache_config:\n        memcached:\n            batch_size: 100\n            parallelism: 100\n        memcached_client:\n            consistent_hash: true\n            host: memcached-index-queries.loki.svc.cluster.local\n            service: memcached-client\ntable_manager:\n    creation_grace_period: 3h\n    poll_interval: 10m\n    retention_deletes_enabled: false\n    retention_period: 0\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"loki","namespace":"loki"}}
  creationTimestamp: "2021-03-12T11:54:00Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:config.yaml: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-03-12T11:54:00Z"
  name: loki
  namespace: loki
  resourceVersion: "4866491"
  selfLink: /api/v1/namespaces/loki/configmaps/loki
  uid: 99965538-3ccd-4c27-902f-90a17c7b8010
