apiVersion: v1
data:
  consul-config.json: '{"leave_on_terminate": true, "telemetry": {"dogstatsd_addr":
    "127.0.0.1:9125"}}'
  mapping: |
    mappings:
    - match: consul.*.runtime.*
      name: consul_runtime
      labels:
        type: $2
    - match: consul.runtime.total_gc_pause_ns
      name: consul_runtime_total_gc_pause_ns
      labels:
        type: $2
    - match: consul.consul.health.service.query-tag.*.*.*
      name: consul_health_service_query_tag
      labels:
        query: $1.$2.$3
    - match: consul.consul.health.service.query-tag.*.*.*.*
      name: consul_health_service_query_tag
      labels:
        query: $1.$2.$3.$4
    - match: consul.consul.health.service.query-tag.*.*.*.*.*
      name: consul_health_service_query_tag
      labels:
        query: $1.$2.$3.$4.$5
    - match: consul.consul.health.service.query-tag.*.*.*.*.*.*
      name: consul_health_service_query_tag
      labels:
        query: $1.$2.$3.$4.$5.$6
    - match: consul.consul.health.service.query-tag.*.*.*.*.*.*.*
      name: consul_health_service_query_tag
      labels:
        query: $1.$2.$3.$4.$5.$6.$7
    - match: consul.consul.health.service.query-tag.*.*.*.*.*.*.*.*
      name: consul_health_service_query_tag
      labels:
        query: $1.$2.$3.$4.$5.$6.$7.$8
    - match: consul.consul.health.service.query-tag.*.*.*.*.*.*.*.*.*
      name: consul_health_service_query_tag
      labels:
        query: $1.$2.$3.$4.$5.$6.$7.$8.$9
    - match: consul.consul.health.service.query-tag.*.*.*.*.*.*.*.*.*.*
      name: consul_health_service_query_tag
      labels:
        query: $1.$2.$3.$4.$5.$6.$7.$8.$9.$10
    - match: consul.consul.health.service.query-tag.*.*.*.*.*.*.*.*.*.*.*
      name: consul_health_service_query_tag
      labels:
        query: $1.$2.$3.$4.$5.$6.$7.$8.$9.$10.$11
    - match: consul.consul.health.service.query-tag.*.*.*.*.*.*.*.*.*.*.*.*
      name: consul_health_service_query_tag
      labels:
        query: $1.$2.$3.$4.$5.$6.$7.$8.$9.$10.$11.$12
    - match: consul.consul.catalog.deregister
      name: consul_catalog_deregister
      labels: {}
    - match: consul.consul.dns.domain_query.*.*.*.*.*
      name: consul_dns_domain_query
      labels:
        query: $1.$2.$3.$4.$5
    - match: consul.consul.health.service.not-found.*
      name: consul_health_service_not_found
      labels:
        query: $1
    - match: consul.consul.health.service.query.*
      name: consul_health_service_query
      labels:
        query: $1
    - match: consul.*.memberlist.health.score
      name: consul_memberlist_health_score
      labels: {}
    - match: consul.serf.queue.*
      name: consul_serf_events
      labels:
        type: $1
    - match: consul.serf.snapshot.appendLine
      name: consul_serf_snapshot_appendLine
      labels:
        type: $1
    - match: consul.serf.coordinate.adjustment-ms
      name: consul_serf_coordinate_adjustment_ms
      labels: {}
    - match: consul.consul.rpc.query
      name: consul_rpc_query
      labels: {}
    - match: consul.*.consul.session_ttl.active
      name: consul_session_ttl_active
      labels: {}
    - match: consul.raft.rpc.*
      name: consul_raft_rpc
      labels:
        type: $1
    - match: consul.raft.rpc.appendEntries.storeLogs
      name: consul_raft_rpc_appendEntries_storeLogs
      labels:
        type: $1
    - match: consul.consul.fsm.persist
      name: consul_fsm_persist
      labels: {}
    - match: consul.raft.fsm.apply
      name: consul_raft_fsm_apply
      labels: {}
    - match: consul.raft.leader.lastContact
      name: consul_raft_leader_lastcontact
      labels: {}
    - match: consul.raft.leader.dispatchLog
      name: consul_raft_leader_dispatchLog
      labels: {}
    - match: consul.raft.commitTime
      name: consul_raft_commitTime
      labels: {}
    - match: consul.raft.replication.appendEntries.logs.*.*.*.*
      name: consul_raft_replication_appendEntries_logs
      labels:
        query: ${1}.${2}.${3}.${4}
    - match: consul.raft.replication.appendEntries.rpc.*.*.*.*
      name: consul_raft_replication_appendEntries_rpc
      labels:
        query: ${1}.${2}.${3}.${4}
    - match: consul.raft.replication.heartbeat.*.*.*.*
      name: consul_raft_replication_heartbeat
      labels:
        query: ${1}.${2}.${3}.${4}
    - match: consul.consul.rpc.request
      name: consul_rpc_requests
      labels: {}
    - match: consul.consul.rpc.accept_conn
      name: consul_rpc_accept_conn
      labels: {}
    - match: consul.memberlist.udp.*
      name: consul_memberlist_udp
      labels:
        type: $1
    - match: consul.memberlist.tcp.*
      name: consul_memberlist_tcp
      labels:
        type: $1
    - match: consul.memberlist.gossip
      name: consul_memberlist_gossip
      labels: {}
    - match: consul.memberlist.probeNode
      name: consul_memberlist_probenode
      labels: {}
    - match: consul.memberlist.pushPullNode
      name: consul_memberlist_pushpullnode
      labels: {}
    - match: consul.http.*
      name: consul_http_request
      labels:
        method: $1
        path: /
    - match: consul.http.*.*
      name: consul_http_request
      labels:
        method: $1
        path: /$2
    - match: consul.http.*.*.*
      name: consul_http_request
      labels:
        method: $1
        path: /$2/$3
    - match: consul.http.*.*.*.*
      name: consul_http_request
      labels:
        method: $1
        path: /$2/$3/$4
    - match: consul.http.*.*.*.*.*
      name: consul_http_request
      labels:
        method: $1
        path: /$2/$3/$4/$5
    - match: consul.consul.leader.barrier
      name: consul_leader_barrier
      labels: {}
    - match: consul.consul.leader.reconcileMember
      name: consul_leader_reconcileMember
      labels: {}
    - match: consul.consul.leader.reconcile
      name: consul_leader_reconcile
      labels: {}
    - match: consul.consul.fsm.coordinate.batch-update
      name: consul_fsm_coordinate_batch_update
      labels: {}
    - match: consul.consul.fsm.autopilot
      name: consul_fsm_autopilot
      labels: {}
    - match: consul.consul.fsm.kvs.cas
      name: consul_fsm_kvs_cas
      labels: {}
    - match: consul.consul.fsm.register
      name: consul_fsm_register
      labels: {}
    - match: consul.consul.fsm.deregister
      name: consul_fsm_deregister
      labels: {}
    - match: consul.consul.fsm.tombstone.reap
      name: consul_fsm_tombstone_reap
      labels: {}
    - match: consul.consul.catalog.register
      name: consul_catalog_register
      labels: {}
    - match: consul.consul.catalog.deregister
      name: consul_catalog_deregister
      labels: {}
    - match: consul.consul.leader.reapTombstones
      name: consul_leader_reapTombstones
      labels: {}
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"consul-config.json":"{\"leave_on_terminate\": true, \"telemetry\": {\"dogstatsd_addr\": \"127.0.0.1:9125\"}}","mapping":"mappings:\n- match: consul.*.runtime.*\n  name: consul_runtime\n  labels:\n    type: $2\n- match: consul.runtime.total_gc_pause_ns\n  name: consul_runtime_total_gc_pause_ns\n  labels:\n    type: $2\n- match: consul.consul.health.service.query-tag.*.*.*\n  name: consul_health_service_query_tag\n  labels:\n    query: $1.$2.$3\n- match: consul.consul.health.service.query-tag.*.*.*.*\n  name: consul_health_service_query_tag\n  labels:\n    query: $1.$2.$3.$4\n- match: consul.consul.health.service.query-tag.*.*.*.*.*\n  name: consul_health_service_query_tag\n  labels:\n    query: $1.$2.$3.$4.$5\n- match: consul.consul.health.service.query-tag.*.*.*.*.*.*\n  name: consul_health_service_query_tag\n  labels:\n    query: $1.$2.$3.$4.$5.$6\n- match: consul.consul.health.service.query-tag.*.*.*.*.*.*.*\n  name: consul_health_service_query_tag\n  labels:\n    query: $1.$2.$3.$4.$5.$6.$7\n- match: consul.consul.health.service.query-tag.*.*.*.*.*.*.*.*\n  name: consul_health_service_query_tag\n  labels:\n    query: $1.$2.$3.$4.$5.$6.$7.$8\n- match: consul.consul.health.service.query-tag.*.*.*.*.*.*.*.*.*\n  name: consul_health_service_query_tag\n  labels:\n    query: $1.$2.$3.$4.$5.$6.$7.$8.$9\n- match: consul.consul.health.service.query-tag.*.*.*.*.*.*.*.*.*.*\n  name: consul_health_service_query_tag\n  labels:\n    query: $1.$2.$3.$4.$5.$6.$7.$8.$9.$10\n- match: consul.consul.health.service.query-tag.*.*.*.*.*.*.*.*.*.*.*\n  name: consul_health_service_query_tag\n  labels:\n    query: $1.$2.$3.$4.$5.$6.$7.$8.$9.$10.$11\n- match: consul.consul.health.service.query-tag.*.*.*.*.*.*.*.*.*.*.*.*\n  name: consul_health_service_query_tag\n  labels:\n    query: $1.$2.$3.$4.$5.$6.$7.$8.$9.$10.$11.$12\n- match: consul.consul.catalog.deregister\n  name: consul_catalog_deregister\n  labels: {}\n- match: consul.consul.dns.domain_query.*.*.*.*.*\n  name: consul_dns_domain_query\n  labels:\n    query: $1.$2.$3.$4.$5\n- match: consul.consul.health.service.not-found.*\n  name: consul_health_service_not_found\n  labels:\n    query: $1\n- match: consul.consul.health.service.query.*\n  name: consul_health_service_query\n  labels:\n    query: $1\n- match: consul.*.memberlist.health.score\n  name: consul_memberlist_health_score\n  labels: {}\n- match: consul.serf.queue.*\n  name: consul_serf_events\n  labels:\n    type: $1\n- match: consul.serf.snapshot.appendLine\n  name: consul_serf_snapshot_appendLine\n  labels:\n    type: $1\n- match: consul.serf.coordinate.adjustment-ms\n  name: consul_serf_coordinate_adjustment_ms\n  labels: {}\n- match: consul.consul.rpc.query\n  name: consul_rpc_query\n  labels: {}\n- match: consul.*.consul.session_ttl.active\n  name: consul_session_ttl_active\n  labels: {}\n- match: consul.raft.rpc.*\n  name: consul_raft_rpc\n  labels:\n    type: $1\n- match: consul.raft.rpc.appendEntries.storeLogs\n  name: consul_raft_rpc_appendEntries_storeLogs\n  labels:\n    type: $1\n- match: consul.consul.fsm.persist\n  name: consul_fsm_persist\n  labels: {}\n- match: consul.raft.fsm.apply\n  name: consul_raft_fsm_apply\n  labels: {}\n- match: consul.raft.leader.lastContact\n  name: consul_raft_leader_lastcontact\n  labels: {}\n- match: consul.raft.leader.dispatchLog\n  name: consul_raft_leader_dispatchLog\n  labels: {}\n- match: consul.raft.commitTime\n  name: consul_raft_commitTime\n  labels: {}\n- match: consul.raft.replication.appendEntries.logs.*.*.*.*\n  name: consul_raft_replication_appendEntries_logs\n  labels:\n    query: ${1}.${2}.${3}.${4}\n- match: consul.raft.replication.appendEntries.rpc.*.*.*.*\n  name: consul_raft_replication_appendEntries_rpc\n  labels:\n    query: ${1}.${2}.${3}.${4}\n- match: consul.raft.replication.heartbeat.*.*.*.*\n  name: consul_raft_replication_heartbeat\n  labels:\n    query: ${1}.${2}.${3}.${4}\n- match: consul.consul.rpc.request\n  name: consul_rpc_requests\n  labels: {}\n- match: consul.consul.rpc.accept_conn\n  name: consul_rpc_accept_conn\n  labels: {}\n- match: consul.memberlist.udp.*\n  name: consul_memberlist_udp\n  labels:\n    type: $1\n- match: consul.memberlist.tcp.*\n  name: consul_memberlist_tcp\n  labels:\n    type: $1\n- match: consul.memberlist.gossip\n  name: consul_memberlist_gossip\n  labels: {}\n- match: consul.memberlist.probeNode\n  name: consul_memberlist_probenode\n  labels: {}\n- match: consul.memberlist.pushPullNode\n  name: consul_memberlist_pushpullnode\n  labels: {}\n- match: consul.http.*\n  name: consul_http_request\n  labels:\n    method: $1\n    path: /\n- match: consul.http.*.*\n  name: consul_http_request\n  labels:\n    method: $1\n    path: /$2\n- match: consul.http.*.*.*\n  name: consul_http_request\n  labels:\n    method: $1\n    path: /$2/$3\n- match: consul.http.*.*.*.*\n  name: consul_http_request\n  labels:\n    method: $1\n    path: /$2/$3/$4\n- match: consul.http.*.*.*.*.*\n  name: consul_http_request\n  labels:\n    method: $1\n    path: /$2/$3/$4/$5\n- match: consul.consul.leader.barrier\n  name: consul_leader_barrier\n  labels: {}\n- match: consul.consul.leader.reconcileMember\n  name: consul_leader_reconcileMember\n  labels: {}\n- match: consul.consul.leader.reconcile\n  name: consul_leader_reconcile\n  labels: {}\n- match: consul.consul.fsm.coordinate.batch-update\n  name: consul_fsm_coordinate_batch_update\n  labels: {}\n- match: consul.consul.fsm.autopilot\n  name: consul_fsm_autopilot\n  labels: {}\n- match: consul.consul.fsm.kvs.cas\n  name: consul_fsm_kvs_cas\n  labels: {}\n- match: consul.consul.fsm.register\n  name: consul_fsm_register\n  labels: {}\n- match: consul.consul.fsm.deregister\n  name: consul_fsm_deregister\n  labels: {}\n- match: consul.consul.fsm.tombstone.reap\n  name: consul_fsm_tombstone_reap\n  labels: {}\n- match: consul.consul.catalog.register\n  name: consul_catalog_register\n  labels: {}\n- match: consul.consul.catalog.deregister\n  name: consul_catalog_deregister\n  labels: {}\n- match: consul.consul.leader.reapTombstones\n  name: consul_leader_reapTombstones\n  labels: {}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"consul","namespace":"loki"}}
  creationTimestamp: "2021-03-12T11:53:59Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:consul-config.json: {}
        f:mapping: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-03-12T11:53:59Z"
  name: consul
  namespace: loki
  resourceVersion: "4866484"
  selfLink: /api/v1/namespaces/loki/configmaps/consul
  uid: 3f057314-89cb-4dc4-a6fd-842788da240d
